### ISSUE TITLE
onBubbleTap not working when app goes to background

### ISSUE THREAD

**Issue by abr13** [moazelsawaf/dash_bubble#1]
onBubbleTap: () async {
print("object");
},
this call is not working when the app is in the background

**Comment by abr13** [comment]
> onBubbleTap: () async { print("object"); }, this call is not working when the app is in the background

await DashBubble.instance.startBubble(
                                                          onBubbleTap:
                                                              () async {
                                                            print("object");
                                                            await LaunchApp
                                                                .isAppInstalled(
                                                                    androidPackageName:
                                                                        'com.example.app');
                                                          },
                                                          options: BubbleOptions(
                                                              keepAliveWhenAppExit:
                                                                  true));
Trying to open the same app

**Comment by moazelsawaf** [comment]
Hello [Abdur Rahman](https://github.com/abr13) 👋🏻

The `onBubbleTap` callback is tested in the foreground and background and should work on both cases, kindly try the [Example Project](https://github.com/moazelsawaf/dash_bubble/tree/main/example) and see if you can reproduce the same issue.

Also you can share me a minimal reproducible example for the issue. 🔁

Thanks 💙

**Comment by abr13** [comment]
Hello @moazelsawaf 

I just tried the example project you quoted, Expected behavior works well when the app is on the screen(onBubbleTap works, prints debug statement and shows a snackbar), but when I close the app and tap on it I don't get anything on my console ie, print('Bubble Tapped'); or neither snackbar(of course!)

Tested Example App:
Ran the example app
> Started the bubble
> Tapped on the bubble > Snackbar appeared with message 'Bubble Tapped' and got printed on the console print('Bubble Tapped');
> Closed the app(just pressed back button/cleared from the recent as well) in wither case
> Now tapped on the bubble: Got nothing on the console
> Again, Opened the app manually(bubble still exists, again tapped on the bubble), this time also no output on the screen(no snackbar and not even console print('Bubble Tapped');)

**Comment by moazelsawaf** [comment]
When you close the app by pressing back when the navigation stack is empty or clearing the app from the recent apps, it terminates the app, so it generally can not handle any action anymore, neither printing nor showing a `SnackBar`.

That is why the parameter `keepAliveWhenAppExit` exists, because when you terminate the app, the bubble will remain alive but with no ability to handle events to trigger the callbacks and execute a Dart code, so if you are planning to fire a callback, then you should set the parameter to `false` (the default value), in order to close the bubble when the app terminates and becomes not able to handle callbacks anymore.

Also, in the last step of your mentioned scenario, when you opened the app with an already shown bubble, the bubble and the app are not connected together because each one is related to a different instance of the app, the already shown bubble is tied to a terminated instance of the app so it can not handle events, and the new instance of the app has no shown bubble yet.

I hope it clears up the misunderstanding. And if you need any help, please do not hesitate to ask me ... 🙏🏻

**Comment by abr13** [comment]
Absolutely, but the expected outcome is not meeting what I wanted to achieve through the bubble (reopening the app on tap) as the documentation does not explain when the onTap action will be valid.

Anyways, can you help me Run the bubble in the background in a separate instance and handle the events as well(just like truecaller/Facebook messenger bubble to reopen the app or maybe trigger some function calls)? :)

**Comment by moazelsawaf** [comment]
Currently you can't perform any callback from Dart side if the app is terminated.

For opening the app while its terminated or brining it to foreground while its working in background, I have already planned to work on this feature and ship it on a future release, but sadly I have no specific time for when it would be released.

If you really need this feature soon, then I advise you to fork the plugin and add a piece of code to open the app from the Native Side while setting the parameter `keepAliveWhenAppExit` to be `false` in the Dart side.

**Comment by abr13** [comment]
Thanks, @moazelsawaf 

I have implemented tap to open or bring to front if already running from the native side (kotlin)
