### ISSUE TITLE
`kotlin-android-extensions` gradle plugin is no longer supported error

### ISSUE THREAD

**Issue by xOldeVx** [moazelsawaf/dash_bubble#2]
When I try to run with the package added to my application, I get the following error:

`kotlin-android-extensions` gradle plugin is no longer supported:

```
Error: The 'kotlin-android-extensions' Gradle plugin is no longer supported. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
e: The Android extensions ('kotlin-android-extensions') compiler plugin is no longer supported. Please use kotlin parcelize and view binding. More information: https://goo.gle/kotlin-android-extensions-deprecation

FAILURE: Build failed with an exception. 

* What went wrong:
Execution failed for task ':dash_bubble:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
    > Compilation error. See log for more details 
```

**Comment by moazelsawaf** [comment]
This issue is because `kotlin-android-extensions` has been deprecated and it was used in the plugin for the `Parcelize` feature in `BubbleOptions` model 🔍

I have migrated the deprecated plugin to the new `kotlin-parcelize` in this [commit ](https://github.com/moazelsawaf/dash_bubble/commit/0d0d9952dd6c5f02fc472d7743e838e7c4f392de) and I think now everything should work fine. ✅

Kindly help me to verify if the issue has been solved or not by changing the dependency in `pubspec.yaml` from: 

```YAML
dependencies:
  . . .
  dash_bubble: ^1.0.0
```

To: 

```YAML
dependencies:
  . . .
  dash_bubble:
    git:
      url: https://github.com/moazelsawaf/dash_bubble.git
      ref: 0d0d9952dd6c5f02fc472d7743e838e7c4f392de
```

And tell me if the issue has been solved or not ... 🙏🏻

If it is solved then you can continue using the plugin this way until I release the new version with the solution very soon Insha'Allah ❤

**Comment by xOldeVx** [comment]
Yes not it's working thanks!
I wanted to use this package for a floating player I see that it is impossible to use it as a player, Just putting pictures in it, wondering for what it's useful

**Comment by moazelsawaf** [comment]
Glad to know that it is working now ❤

For the **Floating Player Use Case**, you can actually use it for that, if the audio/video track is running, then you can use a pause image with the logic to stop the track in the `onTap()` callback, vice versa.

I will close the issue for know because the issue has been solved, If you faced any other issue that is related to this issue, then please don't hesitate to reopen it ✅

And if you want any assistance in the **Floating Player Use Case**, then please add it in the discussion section with all the details and I can help you with that 🙏🏻
